# MS-Windows test job, using latest available version of Emacs from
# MSYS2

name: CI

on:
  push:
    paths-ignore: ['**.adoc']
    branches-ignore: ['future-doc']
  pull_request:
    paths-ignore: ['**.adoc']
    branches-ignore: ['future-doc']

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Set up Emacs
      uses: msys2/setup-msys2@v2
      with:
        release: false
        install: mingw64/mingw-w64-x86_64-emacs
    - run: git config --global core.autocrlf input

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Test the project
      shell: cmd
      run: |        
        %EMACS% --version
        set "ELDEV_LOCAL=%cd%"
        bin\eldev -p -dtTC test --omit-backtraces --expect 200 eldev-help-1
        echo after
        bin\eldev -p -dtTC test --test-type integration --omit-backtraces --expect 5
      env:
        EMACS: "c:\\msys64\\mingw64\\bin\\emacs"
